const en = {
  title: 'Discover', subtitle: 'Useful places for navigating an unfamiliar city', current: 'Current location', selected: 'Selected city', unknown: 'Choose a city to discover local places', change: 'Change context', search: 'Search pharmacy, hospital, transport…', searchAction: 'Search', results: 'Results', cached: 'Showing saved results while providers recover.', attribution: 'Place data sources',
  groups: { essential: 'Essential', services: 'Public and everyday services', support: 'Support' },
  categories: { pharmacy: 'Pharmacy', hospital: 'Healthcare', supermarket: 'Groceries', public_transport: 'Transport', government_office: 'Public services', police: 'Police and safety', bank: 'Banks and ATMs', post_office: 'Post office', language_school: 'Language support', community_center: 'Community resources', job_center: 'Work support' },
  card: { distance: '{{distance}} away', view: 'View details' }, detail: { back: 'Back', address: 'Address', about: 'About', directions: 'Directions', call: 'Call', website: 'Website', ask: 'Ask Naero about this', source: 'Source and provenance' },
  states: { loading: 'Finding places from real providers…', emptyTitle: 'No results found', emptyBody: 'Try another practical category or search term.', offlineTitle: 'Internet connection needed', offlineBody: 'New searches need a connection. Cached results appear when available.', providerTitle: 'Place provider unavailable', providerBody: 'The provider could not answer safely. Try again later.', locationTitle: 'Choose a local context', locationBody: 'Use current location or choose a city manually before searching.', errorTitle: 'Discover could not load', errorBody: 'Nothing has been inferred. Try the request again.', retry: 'Try again' },
};
const ar = {
  title: 'استكشف', subtitle: 'أماكن مفيدة للتنقل في مدينة غير مألوفة', current: 'الموقع الحالي', selected: 'المدينة المختارة', unknown: 'اختر مدينة لاستكشاف الأماكن المحلية', change: 'تغيير السياق', search: 'ابحث عن صيدلية أو مستشفى أو نقل…', searchAction: 'بحث', results: 'النتائج', cached: 'نعرض نتائج محفوظة مؤقتًا حتى يتعافى المزود.', attribution: 'مصادر بيانات الأماكن',
  groups: { essential: 'الأساسيات', services: 'الخدمات العامة واليومية', support: 'الدعم' }, categories: { pharmacy: 'صيدلية', hospital: 'الرعاية الصحية', supermarket: 'البقالة', public_transport: 'النقل', government_office: 'الخدمات العامة', police: 'الشرطة والسلامة', bank: 'البنوك وأجهزة الصراف', post_office: 'مكتب البريد', language_school: 'دعم اللغة', community_center: 'موارد المجتمع', job_center: 'دعم العمل' },
  card: { distance: 'على بعد {{distance}}', view: 'عرض التفاصيل' }, detail: { back: 'رجوع', address: 'العنوان', about: 'نبذة', directions: 'الاتجاهات', call: 'اتصال', website: 'الموقع الإلكتروني', ask: 'اسأل Naero عن هذا المكان', source: 'المصدر والأصل' }, states: { loading: 'نبحث عن أماكن من مزودين حقيقيين…', emptyTitle: 'لا توجد نتائج', emptyBody: 'جرّب فئة عملية أو عبارة بحث أخرى.', offlineTitle: 'يلزم اتصال بالإنترنت', offlineBody: 'تحتاج عمليات البحث الجديدة إلى اتصال. تظهر النتائج المخزنة إن توفرت.', providerTitle: 'مزود الأماكن غير متاح', providerBody: 'تعذّر على المزود الرد بأمان. حاول لاحقًا.', locationTitle: 'اختر سياقًا محليًا', locationBody: 'استخدم موقعك الحالي أو اختر مدينة يدويًا قبل البحث.', errorTitle: 'تعذّر تحميل الاستكشاف', errorBody: 'لم يتم استنتاج أي شيء. حاول الطلب مجددًا.', retry: 'إعادة المحاولة' },
};
const fr = { ...en, title: 'Découvrir', subtitle: 'Des lieux utiles pour s’orienter dans une ville inconnue', current: 'Position actuelle', selected: 'Ville sélectionnée', unknown: 'Choisissez une ville pour découvrir les lieux locaux', change: 'Changer de contexte', search: 'Rechercher pharmacie, hôpital, transport…', searchAction: 'Rechercher', results: 'Résultats', cached: 'Résultats enregistrés affichés pendant le rétablissement du fournisseur.', attribution: 'Sources des données de lieux', groups: { essential: 'Essentiel', services: 'Services publics et quotidiens', support: 'Soutien' }, categories: { pharmacy: 'Pharmacie', hospital: 'Santé', supermarket: 'Courses', public_transport: 'Transport', government_office: 'Services publics', police: 'Police et sécurité', bank: 'Banques et distributeurs', post_office: 'Bureau de poste', language_school: 'Soutien linguistique', community_center: 'Ressources communautaires', job_center: 'Soutien à l’emploi' }, card: { distance: 'À {{distance}}', view: 'Voir les détails' }, detail: { ...en.detail, back: 'Retour', address: 'Adresse', about: 'À propos', directions: 'Itinéraire', call: 'Appeler', website: 'Site web', ask: 'Demander à Naero', source: 'Source et provenance' }, states: { loading: 'Recherche auprès de fournisseurs réels…', emptyTitle: 'Aucun résultat', emptyBody: 'Essayez une autre catégorie ou recherche.', offlineTitle: 'Connexion Internet requise', offlineBody: 'Les nouvelles recherches nécessitent une connexion. Les résultats enregistrés apparaissent si disponibles.', providerTitle: 'Fournisseur indisponible', providerBody: 'Le fournisseur n’a pas pu répondre de façon sûre. Réessayez plus tard.', locationTitle: 'Choisissez un contexte local', locationBody: 'Utilisez votre position ou choisissez une ville avant la recherche.', errorTitle: 'Impossible de charger Découvrir', errorBody: 'Rien n’a été déduit. Réessayez.', retry: 'Réessayer' } };
const hu = { ...en, title: 'Felfedezés', subtitle: 'Hasznos helyek egy ismeretlen városban való eligazodáshoz', current: 'Jelenlegi hely', selected: 'Kiválasztott város', unknown: 'Válassz várost a helyi helyek kereséséhez', change: 'Hely módosítása', search: 'Gyógyszertár, kórház, közlekedés…', searchAction: 'Keresés', results: 'Találatok', cached: 'Mentett találatok megjelenítése, amíg a szolgáltató helyreáll.', attribution: 'Helyadatok forrásai', groups: { essential: 'Alapvető', services: 'Köz- és mindennapi szolgáltatások', support: 'Támogatás' }, categories: { pharmacy: 'Gyógyszertár', hospital: 'Egészségügy', supermarket: 'Élelmiszer', public_transport: 'Közlekedés', government_office: 'Közszolgáltatások', police: 'Rendőrség és biztonság', bank: 'Bankok és ATM-ek', post_office: 'Posta', language_school: 'Nyelvi segítség', community_center: 'Közösségi források', job_center: 'Munkakeresési segítség' }, card: { distance: '{{distance}} távolságra', view: 'Részletek' }, detail: { ...en.detail, back: 'Vissza', address: 'Cím', about: 'Leírás', directions: 'Útvonal', call: 'Hívás', website: 'Webhely', ask: 'Kérdezd Naerót', source: 'Forrás és eredet' }, states: { loading: 'Valós szolgáltatók helyeinek keresése…', emptyTitle: 'Nincs találat', emptyBody: 'Próbálj másik kategóriát vagy keresést.', offlineTitle: 'Internetkapcsolat szükséges', offlineBody: 'Az új keresésekhez kapcsolat kell. A mentett találatok megjelennek, ha vannak.', providerTitle: 'A helyszolgáltató nem érhető el', providerBody: 'A szolgáltató nem tudott biztonságosan válaszolni. Próbáld később.', locationTitle: 'Válassz helyi környezetet', locationBody: 'Keresés előtt használd a jelenlegi helyet vagy válassz várost.', errorTitle: 'A Felfedezés nem tölthető be', errorBody: 'Semmit nem következtettünk ki. Próbáld újra.', retry: 'Újra' } };
module.exports = { en, ar, fr, hu };
