const en = {
  trust: { official: 'Official', naero_verified: 'Naero Verified', external_provider: 'External Provider', community: 'Community', ai_guidance: 'AI Guidance' },
  freshness: { current: 'Current', review_due: 'Review due', outdated: 'Outdated', date_unknown: 'Date unknown', withDate: '{{label}} · {{date}}' },
  jurisdiction: { localityCountry: '{{locality}}, {{country}}', level: '{{name}} — {{level}}', levels: { country: 'National', region: 'Regional', municipality: 'Municipal', service_area: 'Service area' } },
  a11y: { trustLabel: 'Information class: {{label}}', freshnessLabel: 'Freshness: {{label}}', jurisdictionLabel: 'Jurisdiction: {{label}}', openSourceDetails: 'Open source details' },
  source: { title: 'Source details', close: 'Close source details', publisher: 'Publisher', authority: 'Authority', published: 'Published', effective: 'Effective', updated: 'Last updated', verified: 'Naero verified', retrieved: 'Retrieved', language: 'Source language', verificationScope: 'Verification scope', verifierRole: 'Verifier role', aiInvolvement: 'AI involvement', aiInvolved: 'AI was involved in this explanation', assumptions: 'Assumptions', uncertainty: 'Uncertainty', supportingSources: 'Supporting sources', openExternal: 'Open original source', noLink: 'No source link is available', report: 'Report information' },
  states: {
    empty: { generic: { title: 'Nothing here yet', body: 'There is no information to show.' }, saved: { title: 'No saved items', body: 'Items you choose to save will appear here.' }, notifications: { title: 'No notifications', body: 'You have no notifications to review.' } },
    error: { network: { title: 'Connection problem', body: 'Naero could not reach the network. Check your connection and try again.' }, service: { title: 'Service unavailable', body: 'This service is temporarily unavailable.' }, invalid_data: { title: 'Information unavailable', body: 'Naero could not safely display the received information.' }, unavailable: { title: 'Content unavailable', body: 'This content is not available right now.' }, permission: { title: 'Permission needed', body: 'This action needs a permission you have not enabled.' }, unknown: { title: 'Unable to continue', body: 'Naero could not complete this action.' }, reference: 'Reference: {{id}}' },
    offline: { offline: { title: 'You are offline', body: 'Online information is unavailable. Local features still work.' }, cached: { title: 'Offline — saved information available', body: 'Naero is showing information stored on this device.' }, staleCache: { title: 'Offline — older information', body: 'This stored information may no longer be current.' } },
    permission: { location: { title: 'Use your location?', body: 'Location helps Naero find nearby services. You can choose a city instead.', action: 'Enable location' }, notifications: { title: 'Allow notifications?', body: 'Notifications can show updates you choose to follow. Naero remains usable without them.', action: 'Allow notifications' }, camera: { title: 'Allow camera access?', body: 'Camera access is used only for the action you select.', action: 'Allow camera' }, other: { title: 'Permission requested', body: 'This feature needs platform permission. You can continue without it.', action: 'Continue' } },
    locationOff: { title: 'Location is off', body: 'Choose a city manually to keep using local features.', enable: 'Enable location', chooseCity: 'Choose city manually' },
    stale: { review_due: { title: 'Review due', body: 'This information is due for review.' }, outdated: { title: 'Information may be outdated', body: 'Check the original source before acting.' }, checked: 'Last checked {{date}}.', unknownDate: 'The last check date is unknown.', viewSource: 'View source', checkUpdates: 'Check for updates' },
    unsupported: { title: 'Reviewed guidance is not available here yet', body: 'You can still search nearby places and use general Naero features.', discover: 'Explore nearby' },
  },
};

const ar = {
  ...en,
  trust: { official: 'رسمي', naero_verified: 'تحقق منه Naero', external_provider: 'مزود خارجي', community: 'المجتمع', ai_guidance: 'إرشاد بالذكاء الاصطناعي' },
  freshness: { current: 'حالي', review_due: 'يحتاج إلى مراجعة', outdated: 'قديم', date_unknown: 'التاريخ غير معروف', withDate: '{{label}} · {{date}}' },
  jurisdiction: { localityCountry: '{{locality}}، {{country}}', level: '{{name}} — {{level}}', levels: { country: 'وطني', region: 'إقليمي', municipality: 'بلدي', service_area: 'منطقة خدمة' } },
  a11y: { trustLabel: 'فئة المعلومات: {{label}}', freshnessLabel: 'حداثة المعلومات: {{label}}', jurisdictionLabel: 'النطاق: {{label}}', openSourceDetails: 'فتح تفاصيل المصدر' },
  source: { title: 'تفاصيل المصدر', close: 'إغلاق تفاصيل المصدر', publisher: 'الناشر', authority: 'الجهة', published: 'تاريخ النشر', effective: 'تاريخ السريان', updated: 'آخر تحديث', verified: 'تحقق Naero', retrieved: 'تاريخ الاسترجاع', language: 'لغة المصدر', verificationScope: 'نطاق التحقق', verifierRole: 'صفة المدقق', aiInvolvement: 'مشاركة الذكاء الاصطناعي', aiInvolved: 'استُخدم الذكاء الاصطناعي في هذا الشرح', assumptions: 'الافتراضات', uncertainty: 'ما هو غير مؤكد', supportingSources: 'المصادر الداعمة', openExternal: 'فتح المصدر الأصلي', noLink: 'لا يتوفر رابط للمصدر', report: 'الإبلاغ عن المعلومات' },
  states: {
    empty: { generic: { title: 'لا يوجد محتوى بعد', body: 'لا توجد معلومات لعرضها.' }, saved: { title: 'لا توجد عناصر محفوظة', body: 'ستظهر هنا العناصر التي تختار حفظها.' }, notifications: { title: 'لا توجد إشعارات', body: 'ليس لديك إشعارات لمراجعتها.' } },
    error: { network: { title: 'مشكلة في الاتصال', body: 'تعذر على Naero الاتصال بالشبكة. تحقق من اتصالك وحاول مجددًا.' }, service: { title: 'الخدمة غير متاحة', body: 'هذه الخدمة غير متاحة مؤقتًا.' }, invalid_data: { title: 'المعلومات غير متاحة', body: 'تعذر على Naero عرض المعلومات المستلمة بأمان.' }, unavailable: { title: 'المحتوى غير متاح', body: 'هذا المحتوى غير متاح الآن.' }, permission: { title: 'الإذن مطلوب', body: 'يتطلب هذا الإجراء إذنًا لم تقم بتفعيله.' }, unknown: { title: 'تعذر المتابعة', body: 'تعذر على Naero إكمال هذا الإجراء.' }, reference: 'المرجع: {{id}}' },
    offline: { offline: { title: 'أنت غير متصل', body: 'المعلومات عبر الإنترنت غير متاحة. ما زالت الميزات المحلية تعمل.' }, cached: { title: 'غير متصل — تتوفر معلومات محفوظة', body: 'يعرض Naero معلومات مخزنة على هذا الجهاز.' }, staleCache: { title: 'غير متصل — معلومات أقدم', body: 'قد لا تكون هذه المعلومات المخزنة حالية.' } },
    permission: { location: { title: 'هل تريد استخدام موقعك؟', body: 'يساعد الموقع Naero في العثور على خدمات قريبة. يمكنك اختيار مدينة بدلاً من ذلك.', action: 'تفعيل الموقع' }, notifications: { title: 'هل تسمح بالإشعارات؟', body: 'يمكن للإشعارات عرض التحديثات التي تختار متابعتها. يعمل Naero بدونها.', action: 'السماح بالإشعارات' }, camera: { title: 'هل تسمح بالوصول إلى الكاميرا؟', body: 'تُستخدم الكاميرا فقط للإجراء الذي تختاره.', action: 'السماح بالكاميرا' }, other: { title: 'طلب إذن', body: 'تحتاج هذه الميزة إلى إذن من النظام. يمكنك المتابعة بدونه.', action: 'متابعة' } },
    locationOff: { title: 'الموقع متوقف', body: 'اختر مدينة يدويًا لمواصلة استخدام الميزات المحلية.', enable: 'تفعيل الموقع', chooseCity: 'اختيار مدينة يدويًا' },
    stale: { review_due: { title: 'تحتاج إلى مراجعة', body: 'حان موعد مراجعة هذه المعلومات.' }, outdated: { title: 'قد تكون المعلومات قديمة', body: 'تحقق من المصدر الأصلي قبل التصرف.' }, checked: 'آخر تحقق {{date}}.', unknownDate: 'تاريخ آخر تحقق غير معروف.', viewSource: 'عرض المصدر', checkUpdates: 'البحث عن تحديثات' },
    unsupported: { title: 'لا تتوفر إرشادات مراجعة لهذه المنطقة بعد', body: 'ما زال بإمكانك البحث عن الأماكن القريبة واستخدام ميزات Naero العامة.', discover: 'استكشاف القريب' },
  },
};

const fr = JSON.parse(JSON.stringify(en));
Object.assign(fr, {
  trust: { official: 'Officiel', naero_verified: 'Vérifié par Naero', external_provider: 'Fournisseur externe', community: 'Communauté', ai_guidance: 'Conseil de l’IA' },
  freshness: { current: 'À jour', review_due: 'Révision nécessaire', outdated: 'Obsolète', date_unknown: 'Date inconnue', withDate: '{{label}} · {{date}}' },
  jurisdiction: { localityCountry: '{{locality}}, {{country}}', level: '{{name}} — {{level}}', levels: { country: 'National', region: 'Régional', municipality: 'Municipal', service_area: 'Zone de service' } },
  a11y: { trustLabel: 'Classe d’information : {{label}}', freshnessLabel: 'Actualité : {{label}}', jurisdictionLabel: 'Juridiction : {{label}}', openSourceDetails: 'Ouvrir les détails de la source' },
});
Object.assign(fr.source, { title: 'Détails de la source', close: 'Fermer les détails', publisher: 'Éditeur', authority: 'Autorité', published: 'Publié', effective: 'En vigueur', updated: 'Dernière mise à jour', verified: 'Vérifié par Naero', retrieved: 'Consulté', language: 'Langue source', verificationScope: 'Portée de la vérification', verifierRole: 'Rôle du vérificateur', aiInvolvement: 'Intervention de l’IA', aiInvolved: 'L’IA a contribué à cette explication', assumptions: 'Hypothèses', uncertainty: 'Incertitude', supportingSources: 'Sources complémentaires', openExternal: 'Ouvrir la source originale', noLink: 'Aucun lien source disponible', report: 'Signaler ces informations' });
fr.states = {
  empty: { generic: { title: 'Rien à afficher', body: 'Aucune information n’est disponible.' }, saved: { title: 'Aucun élément enregistré', body: 'Les éléments enregistrés apparaîtront ici.' }, notifications: { title: 'Aucune notification', body: 'Vous n’avez aucune notification à consulter.' } },
  error: { network: { title: 'Problème de connexion', body: 'Naero ne peut pas accéder au réseau. Vérifiez votre connexion et réessayez.' }, service: { title: 'Service indisponible', body: 'Ce service est temporairement indisponible.' }, invalid_data: { title: 'Informations indisponibles', body: 'Naero ne peut pas afficher ces informations en toute sécurité.' }, unavailable: { title: 'Contenu indisponible', body: 'Ce contenu n’est pas disponible actuellement.' }, permission: { title: 'Autorisation requise', body: 'Cette action nécessite une autorisation non activée.' }, unknown: { title: 'Impossible de continuer', body: 'Naero n’a pas pu terminer cette action.' }, reference: 'Référence : {{id}}' },
  offline: { offline: { title: 'Vous êtes hors ligne', body: 'Les informations en ligne sont indisponibles. Les fonctions locales restent accessibles.' }, cached: { title: 'Hors ligne — informations enregistrées disponibles', body: 'Naero affiche les informations stockées sur cet appareil.' }, staleCache: { title: 'Hors ligne — informations anciennes', body: 'Ces informations peuvent ne plus être à jour.' } },
  permission: { location: { title: 'Utiliser votre position ?', body: 'La position aide Naero à trouver des services proches. Vous pouvez choisir une ville.', action: 'Activer la position' }, notifications: { title: 'Autoriser les notifications ?', body: 'Les notifications peuvent afficher les mises à jour que vous suivez. Naero fonctionne sans elles.', action: 'Autoriser' }, camera: { title: 'Autoriser l’appareil photo ?', body: 'L’appareil photo est utilisé uniquement pour l’action choisie.', action: 'Autoriser' }, other: { title: 'Autorisation demandée', body: 'Cette fonction nécessite une autorisation système. Vous pouvez continuer sans elle.', action: 'Continuer' } },
  locationOff: { title: 'La position est désactivée', body: 'Choisissez une ville manuellement pour utiliser les fonctions locales.', enable: 'Activer la position', chooseCity: 'Choisir une ville' },
  stale: { review_due: { title: 'Révision nécessaire', body: 'Ces informations doivent être révisées.' }, outdated: { title: 'Informations peut-être obsolètes', body: 'Vérifiez la source originale avant d’agir.' }, checked: 'Dernière vérification : {{date}}.', unknownDate: 'La date de vérification est inconnue.', viewSource: 'Voir la source', checkUpdates: 'Rechercher des mises à jour' },
  unsupported: { title: 'Aucun guide vérifié disponible pour cette zone', body: 'Vous pouvez toujours rechercher des lieux proches et utiliser les fonctions générales.', discover: 'Explorer les environs' },
};

const hu = JSON.parse(JSON.stringify(en));
Object.assign(hu, {
  trust: { official: 'Hivatalos', naero_verified: 'Naero által ellenőrzött', external_provider: 'Külső szolgáltató', community: 'Közösség', ai_guidance: 'MI-útmutatás' },
  freshness: { current: 'Aktuális', review_due: 'Felülvizsgálat esedékes', outdated: 'Elavult', date_unknown: 'Dátum ismeretlen', withDate: '{{label}} · {{date}}' },
  jurisdiction: { localityCountry: '{{locality}}, {{country}}', level: '{{name}} — {{level}}', levels: { country: 'Országos', region: 'Regionális', municipality: 'Önkormányzati', service_area: 'Szolgáltatási terület' } },
  a11y: { trustLabel: 'Információs osztály: {{label}}', freshnessLabel: 'Frissesség: {{label}}', jurisdictionLabel: 'Joghatóság: {{label}}', openSourceDetails: 'Forrás részleteinek megnyitása' },
});
Object.assign(hu.source, { title: 'Forrás részletei', close: 'Forrás részleteinek bezárása', publisher: 'Kiadó', authority: 'Hatóság', published: 'Közzétéve', effective: 'Hatályos', updated: 'Utolsó frissítés', verified: 'Naero ellenőrizte', retrieved: 'Lekérve', language: 'Forrás nyelve', verificationScope: 'Ellenőrzés hatóköre', verifierRole: 'Ellenőrző szerepe', aiInvolvement: 'MI közreműködése', aiInvolved: 'Az MI részt vett ebben a magyarázatban', assumptions: 'Feltételezések', uncertainty: 'Bizonytalanság', supportingSources: 'Támogató források', openExternal: 'Eredeti forrás megnyitása', noLink: 'Nem érhető el forráshivatkozás', report: 'Információ jelentése' });
hu.states = {
  empty: { generic: { title: 'Még nincs itt semmi', body: 'Nincs megjeleníthető információ.' }, saved: { title: 'Nincsenek mentett elemek', body: 'A mentett elemek itt jelennek meg.' }, notifications: { title: 'Nincsenek értesítések', body: 'Nincs áttekintendő értesítése.' } },
  error: { network: { title: 'Kapcsolati probléma', body: 'A Naero nem éri el a hálózatot. Ellenőrizze a kapcsolatot, majd próbálja újra.' }, service: { title: 'A szolgáltatás nem elérhető', body: 'Ez a szolgáltatás átmenetileg nem érhető el.' }, invalid_data: { title: 'Az információ nem elérhető', body: 'A Naero nem tudja biztonságosan megjeleníteni a kapott információt.' }, unavailable: { title: 'A tartalom nem elérhető', body: 'Ez a tartalom jelenleg nem érhető el.' }, permission: { title: 'Engedély szükséges', body: 'Ehhez a művelethez nincs engedélyezve a szükséges hozzáférés.' }, unknown: { title: 'Nem lehet folytatni', body: 'A Naero nem tudta befejezni ezt a műveletet.' }, reference: 'Hivatkozás: {{id}}' },
  offline: { offline: { title: 'Nincs internetkapcsolat', body: 'Az online információ nem érhető el. A helyi funkciók továbbra is működnek.' }, cached: { title: 'Offline — mentett információ elérhető', body: 'A Naero az eszközön tárolt információt mutatja.' }, staleCache: { title: 'Offline — régebbi információ', body: 'A tárolt információ már nem feltétlenül aktuális.' } },
  permission: { location: { title: 'Használja a tartózkodási helyét?', body: 'A helyadat segít közeli szolgáltatásokat találni. Választhat várost is.', action: 'Helyadat engedélyezése' }, notifications: { title: 'Engedélyezi az értesítéseket?', body: 'Az értesítések a követett frissítéseket mutatják. A Naero nélkülük is használható.', action: 'Értesítések engedélyezése' }, camera: { title: 'Engedélyezi a kamerát?', body: 'A kamera csak a kiválasztott művelethez használható.', action: 'Kamera engedélyezése' }, other: { title: 'Engedélykérés', body: 'Ehhez a funkcióhoz rendszerengedély kell. Nélküle is folytathatja.', action: 'Folytatás' } },
  locationOff: { title: 'A helyadat ki van kapcsolva', body: 'Válasszon várost kézzel a helyi funkciók használatához.', enable: 'Helyadat engedélyezése', chooseCity: 'Város kiválasztása' },
  stale: { review_due: { title: 'Felülvizsgálat esedékes', body: 'Ezt az információt felül kell vizsgálni.' }, outdated: { title: 'Az információ elavult lehet', body: 'Művelet előtt ellenőrizze az eredeti forrást.' }, checked: 'Utolsó ellenőrzés: {{date}}.', unknownDate: 'Az utolsó ellenőrzés dátuma ismeretlen.', viewSource: 'Forrás megtekintése', checkUpdates: 'Frissítések keresése' },
  unsupported: { title: 'Ehhez a területhez még nincs ellenőrzött útmutató', body: 'Továbbra is kereshet közeli helyeket és használhatja az általános funkciókat.', discover: 'Közeli helyek felfedezése' },
};

module.exports = { en, ar, fr, hu };
