import React, { useState } from 'react';
import { I18nManager, Linking, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Text from '../components/Text';
import SourceSummary from '../components/contextual/SourceSummary';
import SourceSheet from '../components/contextual/SourceSheet';
import { useThemeMode } from '../theme/ThemeModeContext';

function Action({ icon, label, onPress, theme }) { return <Pressable onPress={onPress} accessibilityRole="button" accessibilityLabel={label} style={({ pressed }) => [styles.action, { borderColor: theme.colors.border.default, minHeight: theme.touchTargets.preferred, opacity: pressed ? 0.8 : 1 }]}><Ionicons name={icon} size={theme.icons.inline} color={theme.colors.action.primary} /><Text variant="captionBold" style={{ color: theme.colors.text.primary }}>{label}</Text></Pressable>; }
export default function ContextualDiscoverDetailScreen({ route, navigation }) {
  const { item, context } = route.params; const { t, i18n } = useTranslation(); const { theme } = useThemeMode(); const insets = useSafeAreaInsets(); const rtl = i18n.language === 'ar'; const [sourceOpen, setSourceOpen] = useState(false);
  const open = async (url) => { try { if (url && await Linking.canOpenURL(url)) await Linking.openURL(url); } catch {} };
  return <View style={{ flex: 1, backgroundColor: theme.colors.background.canvas }}><ScrollView contentContainerStyle={{ paddingTop: insets.top + 12, paddingBottom: insets.bottom + 32, paddingHorizontal: 20, gap: 20 }}><Pressable onPress={() => navigation.goBack()} accessibilityRole="button" accessibilityLabel={t('compass3d.detail.back')} style={[styles.back, { minWidth: theme.touchTargets.minimum, minHeight: theme.touchTargets.minimum }]}><Ionicons name={rtl ? 'arrow-forward' : 'arrow-back'} size={theme.icons.control} color={theme.colors.text.primary} /></Pressable><View style={styles.heading}><Text variant="h1" accessibilityRole="header" style={[{ color: theme.colors.text.primary }, rtl && styles.rtl]}>{item.name}</Text><Text variant="body" style={[{ color: theme.colors.text.secondary }, rtl && styles.rtl]}>{t(`compass3d.categories.${item.category}`)}</Text>{context?.label ? <Text variant="caption" style={[{ color: theme.colors.text.secondary }, rtl && styles.rtl]}>{context.label}</Text> : null}</View>{item.address ? <View style={[styles.info, rtl && styles.rowReverse]}><Ionicons name="location-outline" size={theme.icons.inline} color={theme.colors.action.primary} /><View style={styles.flex}><Text variant="captionBold" style={[{ color: theme.colors.text.secondary }, rtl && styles.rtl]}>{t('compass3d.detail.address')}</Text><Text variant="body" style={[{ color: theme.colors.text.primary }, rtl && styles.rtl]}>{item.address}</Text></View></View> : null}{item.description ? <View style={styles.heading}><Text variant="h3" style={[{ color: theme.colors.text.primary }, rtl && styles.rtl]}>{t('compass3d.detail.about')}</Text><Text variant="body" style={[{ color: theme.colors.text.secondary }, rtl && styles.rtl]}>{item.description}</Text></View> : null}<View style={[styles.actions, rtl && styles.rowReverse]}>{item.directionsUrl ? <Action icon="navigate-outline" label={t('compass3d.detail.directions')} onPress={() => open(item.directionsUrl)} theme={theme} /> : null}{item.phone ? <Action icon="call-outline" label={t('compass3d.detail.call')} onPress={() => open(`tel:${item.phone.replace(/[^+\d]/g, '')}`)} theme={theme} /> : null}{item.website ? <Action icon="globe-outline" label={t('compass3d.detail.website')} onPress={() => open(item.website)} theme={theme} /> : null}<Action icon="sparkles-outline" label={t('compass3d.detail.ask')} onPress={() => navigation.navigate('AI', { discoverContext: { name: item.name, category: item.category, city: context?.label || null, sourceType: item.provenance?.trustClass } })} theme={theme} /></View><Text variant="h3" style={[{ color: theme.colors.text.primary }, rtl && styles.rtl]}>{t('compass3d.detail.source')}</Text><SourceSummary provenance={item.provenance} locale={i18n.language} compact={false} onPress={() => setSourceOpen(true)} /></ScrollView><SourceSheet visible={sourceOpen} provenance={item.provenance} locale={i18n.language} onClose={() => setSourceOpen(false)} /></View>;
}
const styles = StyleSheet.create({ back: { alignSelf: 'flex-start', alignItems: 'center', justifyContent: 'center' }, heading: { gap: 6 }, rtl: { textAlign: 'right', writingDirection: 'rtl' }, rowReverse: { flexDirection: 'row-reverse' }, info: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' }, flex: { flex: 1 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, action: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1, borderRadius: 8 } });
